// <auto-generated />
using System;
using Backend_schronisko.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_schronisko.Migrations
{
    [DbContext(typeof(SchroniskoContext))]
    [Migration("20260603191345_ZmianaNaGosciaIPracownikow")]
    partial class ZmianaNaGosciaIPracownikow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_schronisko.Models.Gatunek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gatunki");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Pies"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Kot"
                        });
                });

            modelBuilder.Entity("Backend_schronisko.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Haslo = "gosc123",
                            Login = "gosc",
                            Rola = "gosc"
                        },
                        new
                        {
                            Id = 2,
                            Haslo = "haslo123",
                            Login = "pracownik1",
                            Rola = "pracownik"
                        },
                        new
                        {
                            Id = 3,
                            Haslo = "haslo123",
                            Login = "pracownik2",
                            Rola = "pracownik"
                        });
                });

            modelBuilder.Entity("Backend_schronisko.Models.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akceptuje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choroby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzyKastrowanySterylizowany")
                        .HasColumnType("bit");

                    b.Property<bool>("CzySzczepiony")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZachipowany")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataPrzyjecia")
                        .HasColumnType("datetime2");

                    b.Property<int>("GatunekId")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerBoksu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumerChip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerEwidencyjny")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrzyblizonaDataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rasa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Umaszczenie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wielkosc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Zachowanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZdjecieUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GatunekId");

                    b.ToTable("Zwierzeta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Akceptuje = "Inne psy, starsze dzieci",
                            Choroby = "Brak",
                            CzyKastrowanySterylizowany = true,
                            CzySzczepiony = true,
                            CzyZachipowany = true,
                            DataPrzyjecia = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 1,
                            Imie = "Burek",
                            NumerBoksu = "B12",
                            NumerChip = "982000000123456",
                            NumerEwidencyjny = "P-2026-001",
                            Plec = "Samiec",
                            PrzyblizonaDataUrodzenia = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "Mieszaniec",
                            Status = "Do adopcji",
                            Umaszczenie = "Czarno-podpalane",
                            Wielkosc = "Średnia",
                            Zachowanie = "Przyjazny, energiczny, lubi spacery",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1543466835-00a7907e9de1"
                        },
                        new
                        {
                            Id = 2,
                            Akceptuje = "Tylko dorośli",
                            Choroby = "Niedowaga, zapalenie ucha",
                            CzyKastrowanySterylizowany = false,
                            CzySzczepiony = false,
                            CzyZachipowany = false,
                            DataPrzyjecia = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 1,
                            Imie = "Luna",
                            NumerBoksu = "Szpitalik",
                            NumerEwidencyjny = "P-2026-002",
                            Plec = "Samica",
                            PrzyblizonaDataUrodzenia = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "W typie owczarka",
                            Status = "W trakcie leczenia",
                            Umaszczenie = "Wilczaste",
                            Wielkosc = "Duża",
                            Zachowanie = "Lękliwa, wycofana, wymaga cierpliwości",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e"
                        },
                        new
                        {
                            Id = 3,
                            Akceptuje = "Koty, psy, dzieci",
                            Choroby = "Alergia pokarmowa",
                            CzyKastrowanySterylizowany = true,
                            CzySzczepiony = true,
                            CzyZachipowany = true,
                            DataPrzyjecia = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 1,
                            Imie = "Reksio",
                            NumerBoksu = "A4",
                            NumerChip = "982000000654321",
                            NumerEwidencyjny = "P-2026-003",
                            Plec = "Samiec",
                            PrzyblizonaDataUrodzenia = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "Jack Russell Terrier mix",
                            Status = "Zarezerwowany",
                            Umaszczenie = "Biało-brązowe",
                            Wielkosc = "Mała",
                            Zachowanie = "Bardzo aktywny, głośny, uwielbia zabawki",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1537151608804-ea2f1fae5e6e"
                        },
                        new
                        {
                            Id = 4,
                            Akceptuje = "Inne koty",
                            Choroby = "Brak",
                            CzyKastrowanySterylizowany = true,
                            CzySzczepiony = true,
                            CzyZachipowany = true,
                            DataPrzyjecia = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 2,
                            Imie = "Filemon",
                            NumerBoksu = "Kociarnia 1",
                            NumerChip = "982000000111222",
                            NumerEwidencyjny = "K-2026-001",
                            Plec = "Samiec",
                            PrzyblizonaDataUrodzenia = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "Europejska",
                            Status = "Do adopcji",
                            Umaszczenie = "Biało-czarne",
                            Wielkosc = "Mała",
                            Zachowanie = "Miziasty, ciągle mruczy, domaga się uwagi",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba"
                        },
                        new
                        {
                            Id = 5,
                            Akceptuje = "Brak danych",
                            Choroby = "Katar koci (leczony)",
                            CzyKastrowanySterylizowany = true,
                            CzySzczepiony = false,
                            CzyZachipowany = true,
                            DataPrzyjecia = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 2,
                            Imie = "Kropka",
                            NumerBoksu = "Klatka 3",
                            NumerChip = "982000000333444",
                            NumerEwidencyjny = "K-2026-002",
                            Plec = "Samica",
                            PrzyblizonaDataUrodzenia = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "Europejska",
                            Status = "Kwarantanna",
                            Umaszczenie = "Szylkretowe",
                            Wielkosc = "Średnia",
                            Zachowanie = "Spokojna, głównie śpi, ceni przestrzeń",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8"
                        },
                        new
                        {
                            Id = 6,
                            Akceptuje = "Wymaga bycia jedynakiem",
                            Choroby = "Zdiagnozowana niewydolność nerek - wymaga karmy Renal",
                            CzyKastrowanySterylizowany = true,
                            CzySzczepiony = true,
                            CzyZachipowany = true,
                            DataPrzyjecia = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GatunekId = 2,
                            Imie = "Mruczek",
                            NumerBoksu = "Kociarnia 2",
                            NumerChip = "982000000555666",
                            NumerEwidencyjny = "K-2026-003",
                            Plec = "Samiec",
                            PrzyblizonaDataUrodzenia = new DateTime(2018, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rasa = "Brytyjski (mix)",
                            Status = "Do adopcji",
                            Umaszczenie = "Niebieskie",
                            Wielkosc = "Duża",
                            Zachowanie = "Wielki pieszczoch, ale tylko na własnych zasadach",
                            ZdjecieUrl = "https://images.unsplash.com/photo-1495360010541-f48722b34f7d"
                        });
                });

            modelBuilder.Entity("Backend_schronisko.Models.Zwierze", b =>
                {
                    b.HasOne("Backend_schronisko.Models.Gatunek", "Gatunek")
                        .WithMany()
                        .HasForeignKey("GatunekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gatunek");
                });
#pragma warning restore 612, 618
        }
    }
}
