// <auto-generated />
using System;
using Backend_schronisko.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_schronisko.Migrations
{
    [DbContext(typeof(SchroniskoContext))]
    partial class SchroniskoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_schronisko.Models.Gatunek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gatunki");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Pies"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Kot"
                        });
                });

            modelBuilder.Entity("Backend_schronisko.Models.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akceptuje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choroby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzyKastrowanySterylizowany")
                        .HasColumnType("bit");

                    b.Property<bool>("CzySzczepiony")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZachipowany")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataPrzyjecia")
                        .HasColumnType("datetime2");

                    b.Property<int>("GatunekId")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerBoksu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumerChip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerEwidencyjny")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrzyblizonaDataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rasa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Umaszczenie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wielkosc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Zachowanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZdjecieUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GatunekId");

                    b.ToTable("Zwierzeta");
                });

            modelBuilder.Entity("Backend_schronisko.Models.Zwierze", b =>
                {
                    b.HasOne("Backend_schronisko.Models.Gatunek", "Gatunek")
                        .WithMany()
                        .HasForeignKey("GatunekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gatunek");
                });
#pragma warning restore 612, 618
        }
    }
}
